/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.core.msfmainapp.client.admin.dto.system;

import java.io.Serializable;

// Generated 3-mar-2011 10.09.19 by Hibernate Tools 3.2.4.GA


/**
 * AdmProfiles generated by hbm2java
 */
public class MSFAuthCheckDTO implements  Serializable {

	  private static final long serialVersionUID = 1L;
	  
	        private java.lang.String dpobCd; 
			private java.lang.String sysDivCd; 
			private java.lang.String usrId; 
			private java.lang.String usrDivCd; 
			
			private java.lang.String authCheck01;    //단위기관 
			private java.lang.String authCheck02;    //고용구분
			private java.lang.String authCheck03;    //부서
			private java.lang.String authCheck04;    //직종
			private java.lang.String authCheck05;    //직종세
			private java.lang.String authCheck06;    //사업
			private java.lang.String authCheck07;    //""
			private java.lang.String authCheck08;
			private java.lang.String authCheck09; 
			private java.lang.String authCheck10;

    public MSFAuthCheckDTO() {
    }

    public MSFAuthCheckDTO(String dpobCd
    		          , String sysDivCd
    		          , String usrId
    		          , String usrDivCd
    		          , String authCheck01
    		          , String authCheck02
    		          , String authCheck03
    		          , String authCheck04
    		          , String authCheck05
    		          , String authCheck06
    		          , String authCheck07
    		          , String authCheck08
    		          , String authCheck09
    		          , String authCheck10
    		          
    		 ) {
        this.dpobCd = dpobCd;
        this.sysDivCd = sysDivCd;
        this.usrId = usrId;
        this.usrDivCd = usrDivCd;
        this.authCheck01 = authCheck01;
        this.authCheck02 = authCheck02;
        this.authCheck03 = authCheck03;
        this.authCheck04 = authCheck04;
        this.authCheck05 = authCheck05;
        this.authCheck06 = authCheck06;
        this.authCheck07 = authCheck07;
        this.authCheck08 = authCheck08;
        this.authCheck09 = authCheck09;
        this.authCheck10 = authCheck10;
    }

	public java.lang.String getDpobCd() {
		return dpobCd;
	}

	public void setDpobCd(java.lang.String dpobCd) {
		this.dpobCd = dpobCd;
	}

	public java.lang.String getSysDivCd() {
		return sysDivCd;
	}

	public void setSysDivCd(java.lang.String sysDivCd) {
		this.sysDivCd = sysDivCd;
	}

	public java.lang.String getUsrId() {
		return usrId;
	}

	public void setUsrId(java.lang.String usrId) {
		this.usrId = usrId;
	}

	public java.lang.String getUsrDivCd() {
		return usrDivCd;
	}

	public void setUsrDivCd(java.lang.String usrDivCd) {
		this.usrDivCd = usrDivCd;
	}

	public java.lang.String getAuthCheck01() {
		return authCheck01;
	}

	public void setAuthCheck01(java.lang.String authCheck01) {
		this.authCheck01 = authCheck01;
	}

	public java.lang.String getAuthCheck02() {
		return authCheck02;
	}

	public void setAuthCheck02(java.lang.String authCheck02) {
		this.authCheck02 = authCheck02;
	}

	public java.lang.String getAuthCheck03() {
		return authCheck03;
	}

	public void setAuthCheck03(java.lang.String authCheck03) {
		this.authCheck03 = authCheck03;
	}

	public java.lang.String getAuthCheck04() {
		return authCheck04;
	}

	public void setAuthCheck04(java.lang.String authCheck04) {
		this.authCheck04 = authCheck04;
	}

	public java.lang.String getAuthCheck05() {
		return authCheck05;
	}

	public void setAuthCheck05(java.lang.String authCheck05) {
		this.authCheck05 = authCheck05;
	}

	public java.lang.String getAuthCheck06() {
		return authCheck06;
	}

	public void setAuthCheck06(java.lang.String authCheck06) {
		this.authCheck06 = authCheck06;
	}

	public java.lang.String getAuthCheck07() {
		return authCheck07;
	}

	public void setAuthCheck07(java.lang.String authCheck07) {
		this.authCheck07 = authCheck07;
	}

	public java.lang.String getAuthCheck08() {
		return authCheck08;
	}

	public void setAuthCheck08(java.lang.String authCheck08) {
		this.authCheck08 = authCheck08;
	}

	public java.lang.String getAuthCheck09() {
		return authCheck09;
	}

	public void setAuthCheck09(java.lang.String authCheck09) {
		this.authCheck09 = authCheck09;
	}

	public java.lang.String getAuthCheck10() {
		return authCheck10;
	}

	public void setAuthCheck10(java.lang.String authCheck10) {
		this.authCheck10 = authCheck10;
	}
      
 
     
}
