package com.app.exterms.payroll.client.dto;

import com.extjs.gxt.ui.client.data.BaseModel;

public class Payr4700DTO extends BaseModel{
	
	private static final long serialVersionUID = 1L;
	
	public Payr4700DTO(){}
	
	//순번이 필요할경우
	public void setRnum(String rnum) { set("rnum", rnum); }
	public String getRnum(){return (String)get("rnum");}
	
	/** set 사업장코드 : dpobCd */
	public void setDpobCd(String dpobCd) { set("dpobCd",dpobCd);}
	/** get 사업장코드 : dpobCd */
	public String getDpobCd() { return (String)get("dpobCd");}
	/** set 원천징수발급번호 : whdgTxIssNum */
	public void setWhdgTxIssNum(String whdgTxIssNum) { set("whdgTxIssNum",whdgTxIssNum);}
	/** get 원천징수발급번호 : whdgTxIssNum */
	public String getWhdgTxIssNum() { return (String)get("whdgTxIssNum");}
	/** set 원천징수발급년도 : whdgTxIssYr */
	public void setWhdgTxIssYr(String whdgTxIssYr) { set("whdgTxIssYr",whdgTxIssYr);}
	/** get 원천징수발급년도 : whdgTxIssYr */
	public String getWhdgTxIssYr() { return (String)get("whdgTxIssYr");}
	/** set 증명서발급구분코드 : certcIssDivCd */
	public void setCertcIssDivCd(String certcIssDivCd) { set("certcIssDivCd",certcIssDivCd);}
	/** get 증명서발급구분코드 : certcIssDivCd */
	public String getCertcIssDivCd() { return (String)get("certcIssDivCd");}
	/** set SYSTEMKEY : systemkey */
	public void setSystemkey(String systemkey) { set("systemkey",systemkey);}
	/** get SYSTEMKEY : systemkey */
	public String getSystemkey() { return (String)get("systemkey");}
	/** set 원천징수발급일자 : whdgTxIssDt */
	public void setWhdgTxIssDt(String whdgTxIssDt) { set("whdgTxIssDt",whdgTxIssDt);}
	/** get 원천징수발급일자 : whdgTxIssDt */
	public String getWhdgTxIssDt() { return (String)get("whdgTxIssDt");}
	/** set 원천징수발급부수 : whdgTxIssNumCpis */
	public void setWhdgTxIssNumCpis(String whdgTxIssNumCpis) { set("whdgTxIssNumCpis",whdgTxIssNumCpis);}
	/** get 원천징수발급부수 : whdgTxIssNumCpis */
	public String getWhdgTxIssNumCpis() { return (String)get("whdgTxIssNumCpis");}
	/** set 원천징수발급용도내용 : whdgTxIssPrpseCtnt */
	public void setWhdgTxIssPrpseCtnt(String whdgTxIssPrpseCtnt) { set("whdgTxIssPrpseCtnt",whdgTxIssPrpseCtnt);}
	/** get 원천징수발급용도내용 : whdgTxIssPrpseCtnt */
	public String getWhdgTxIssPrpseCtnt() { return (String)get("whdgTxIssPrpseCtnt");}
	/** set 원천징수발급기관명 : whdgTxIssIstutNm */
	public void setWhdgTxIssIstutNm(String whdgTxIssIstutNm) { set("whdgTxIssIstutNm",whdgTxIssIstutNm);}
	/** get 원천징수발급기관명 : whdgTxIssIstutNm */
	public String getWhdgTxIssIstutNm() { return (String)get("whdgTxIssIstutNm");}
	/** set 원천징수발급신청일자 : whdgTxIssAppyDt */
	public void setWhdgTxIssAppyDt(String whdgTxIssAppyDt) { set("whdgTxIssAppyDt",whdgTxIssAppyDt);}
	/** get 원천징수발급신청일자 : whdgTxIssAppyDt */
	public String getWhdgTxIssAppyDt() { return (String)get("whdgTxIssAppyDt");}
	/** set 원천징수발급승인일자 : whdgTxIssAppbnDt */
	public void setWhdgTxIssAppbnDt(String whdgTxIssAppbnDt) { set("whdgTxIssAppbnDt",whdgTxIssAppbnDt);}
	/** get 원천징수발급승인일자 : whdgTxIssAppbnDt */
	public String getWhdgTxIssAppbnDt() { return (String)get("whdgTxIssAppbnDt");}
	/** set 원천징수발급상태구분코드 : whdgTxIssCodTNDivCd */
	public void setWhdgTxIssCodTNDivCd(String whdgTxIssCodTNDivCd) { set("whdgTxIssCodTNDivCd",whdgTxIssCodTNDivCd);}
	/** get 원천징수발급상태구분코드 : whdgTxIssCodTNDivCd */
	public String getWhdgTxIssCodTNDivCd() { return (String)get("whdgTxIssCodTNDivCd");}
	/** set 원천징수발급여부 : whdgTxIssYn */
	public void setWhdgTxIssYn(String whdgTxIssYn) { set("whdgTxIssYn",whdgTxIssYn);}
	/** get 원천징수발급여부 : whdgTxIssYn */
	public String getWhdgTxIssYn() { return (String)get("whdgTxIssYn");}
	/** set 원천징수발급삭제여부 : whdgTxIssDelYn */
	public void setWhdgTxIssDelYn(String whdgTxIssDelYn) { set("whdgTxIssDelYn",whdgTxIssDelYn);}
	/** get 원천징수발급삭제여부 : whdgTxIssDelYn */
	public String getWhdgTxIssDelYn() { return (String)get("whdgTxIssDelYn");}
	/** set 입력자 : kybdr */
	public void setKybdr(String kybdr) { set("kybdr",kybdr);}
	/** get 입력자 : kybdr */
	public String getKybdr() { return (String)get("kybdr");}
	/** set 입력일자 : inptDt */
	public void setInptDt(String inptDt) { set("inptDt",inptDt);}
	/** get 입력일자 : inptDt */
	public String getInptDt() { return (String)get("inptDt");}
	/** set 입력주소 : inptAddr */
	public void setInptAddr(String inptAddr) { set("inptAddr",inptAddr);}
	/** get 입력주소 : inptAddr */
	public String getInptAddr() { return (String)get("inptAddr");}
	/** set 수정자 : ismt */
	public void setIsmt(String ismt) { set("ismt",ismt);}
	/** get 수정자 : ismt */
	public String getIsmt() { return (String)get("ismt");}
	/** set 수정일자 : revnDt */
	public void setRevnDt(String revnDt) { set("revnDt",revnDt);}
	/** get 수정일자 : revnDt */
	public String getRevnDt() { return (String)get("revnDt");}
	/** set 수정주소 : revnAddr */
	public void setRevnAddr(String revnAddr) { set("revnAddr",revnAddr);}
	/** get 수정주소 : revnAddr */
	public String getRevnAddr() { return (String)get("revnAddr");}

	
	/** set 한글성명 : hanNm */
	public void setHanNm(String hanNm) { set("hanNm",hanNm);}
	/** get 한글성명 : hanNm */
	public String getHanNm() { return (String)get("hanNm");}
	/** set 영문성명 : engNm */
	public void setEngNm(String engNm) { set("engNm",engNm);}
	/** get 영문성명 : engNm */
	public String getEngNm() { return (String)get("engNm");}
	/** set 한문성명 : chinCharNm */
	public void setChinCharNm(String chinCharNm) { set("chinCharNm",chinCharNm);}
	/** get 한문성명 : chinCharNm */
	public String getChinCharNm() { return (String)get("chinCharNm");}
	/** set 주민등록번호 : resnRegnNum */
	public void setResnRegnNum(String resnRegnNum) { set("resnRegnNum",resnRegnNum);}
	/** get 주민등록번호 : resnRegnNum */
	public String getResnRegnNum() { return (String)get("resnRegnNum");}
	
	/** set 원본 주민등록번호 : secRegnNum */
	public void setSecRegnNum(String secRegnNum) { set("secRegnNum",secRegnNum);}
	/** get 원본 주민등록번호 : secRegnNum */
	public String getSecRegnNum() { return (String)get("secRegnNum");}
	
	
	/** set 성별구분코드 : sxDivCd */
	public void setSxDivCd(String sxDivCd) { set("sxDivCd",sxDivCd);}
	/** get 성별구분코드 : sxDivCd */
	public String getSxDivCd() { return (String)get("sxDivCd");}
	/** set 생년월일 : yoobhMnthDay */
	public void setYoobhMnthDay(String yoobhMnthDay) { set("yoobhMnthDay",yoobhMnthDay);}
	/** get 생년월일 : yoobhMnthDay */
	public String getYoobhMnthDay() { return (String)get("yoobhMnthDay");}
	/** set 음양구분코드 : sclcDivCd */
	public void setSclcDivCd(String sclcDivCd) { set("sclcDivCd",sclcDivCd);}
	/** get 음양구분코드 : sclcDivCd */
	public String getSclcDivCd() { return (String)get("sclcDivCd");}
	/** set 국가코드 : natnCd */
	public void setNatnCd(String natnCd) { set("natnCd",natnCd);}
	/** get 국가코드 : natnCd */
	public String getNatnCd() { return (String)get("natnCd");}
	/** set 부서코드 : deptCd */
	public void setDeptCd(String deptCd) { set("deptCd",deptCd);}
	/** get 부서코드 : deptCd */
	public String getDeptCd() { return (String)get("deptCd");}
	/** set 사업코드 : businCd */
	public void setBusinCd(String businCd) { set("businCd",businCd);}
	/** get 사업코드 : businCd */
	public String getBusinCd() { return (String)get("businCd");}
	/** set 현소속부서코드 : currAffnDeptCd */
	public void setCurrAffnDeptCd(String currAffnDeptCd) { set("currAffnDeptCd",currAffnDeptCd);}
	/** get 현소속부서코드 : currAffnDeptCd */
	public String getCurrAffnDeptCd() { return (String)get("currAffnDeptCd");}
	/** set 담당업무구분코드 : repbtyBusinDivCd */
	public void setRepbtyBusinDivCd(String repbtyBusinDivCd) { set("repbtyBusinDivCd",repbtyBusinDivCd);}
	/** get 담당업무구분코드 : repbtyBusinDivCd */
	public String getRepbtyBusinDivCd() { return (String)get("repbtyBusinDivCd");}
	/** set 직종코드 : typOccuCd */
	public void setTypOccuCd(String typOccuCd) { set("typOccuCd",typOccuCd);}
	/** get 직종코드 : typOccuCd */
	public String getTypOccuCd() { return (String)get("typOccuCd");}
	/** set 직책코드 : odtyCd */
	public void setOdtyCd(String odtyCd) { set("odtyCd",odtyCd);}
	/** get 직책코드 : odtyCd */
	public String getOdtyCd() { return (String)get("odtyCd");}
	/** set 최초고용일자 : frstEmymtDt */
	public void setFrstEmymtDt(String frstEmymtDt) { set("frstEmymtDt",frstEmymtDt);}
	/** get 최초고용일자 : frstEmymtDt */
	public String getFrstEmymtDt() { return (String)get("frstEmymtDt");}
	/** set 고용구분코드 : emymtDivCd */
	public void setEmymtDivCd(String emymtDivCd) { set("emymtDivCd",emymtDivCd);}
	/** get 고용구분코드 : emymtDivCd */
	public String getEmymtDivCd() { return (String)get("emymtDivCd");}
	/** set 고용시작일자 : emymtBgnnDt */
	public void setEmymtBgnnDt(String emymtBgnnDt) { set("emymtBgnnDt",emymtBgnnDt);}
	/** get 고용시작일자 : emymtBgnnDt */
	public String getEmymtBgnnDt() { return (String)get("emymtBgnnDt");}
	/** set 고용종료일자 : emymtEndDt */
	public void setEmymtEndDt(String emymtEndDt) { set("emymtEndDt",emymtEndDt);}
	/** get 고용종료일자 : emymtEndDt */
	public String getEmymtEndDt() { return (String)get("emymtEndDt");}
	/** set 호봉코드 : pyspCd */
	public void setPyspCd(String pyspCd) { set("pyspCd",pyspCd);}
	/** get 호봉코드 : pyspCd */
	public String getPyspCd() { return (String)get("pyspCd");}
	/** set 재직상태코드 : hdofcCodtnCd */
	public void setHdofcCodtnCd(String hdofcCodtnCd) { set("hdofcCodtnCd",hdofcCodtnCd);}
	/** get 재직상태코드 : hdofcCodtnCd */
	public String getHdofcCodtnCd() { return (String)get("hdofcCodtnCd");}
	/** set 퇴직일자 : retryDt */
	public void setRetryDt(String retryDt) { set("retryDt",retryDt);}
	/** get 퇴직일자 : retryDt */
	public String getRetryDt() { return (String)get("retryDt");}
	/** set 퇴직사유내용 : retryReasCtnt */
	public void setRetryReasCtnt(String retryReasCtnt) { set("retryReasCtnt",retryReasCtnt);}
	/** get 퇴직사유내용 : retryReasCtnt */
	public String getRetryReasCtnt() { return (String)get("retryReasCtnt");}
	/** set 외국인구분코드 : frgnrDivCd */
	public void setFrgnrDivCd(String frgnrDivCd) { set("frgnrDivCd",frgnrDivCd);}
	/** get 외국인구분코드 : frgnrDivCd */
	public String getFrgnrDivCd() { return (String)get("frgnrDivCd");}
	/** set 여권번호 : psptNum */
	public void setPsptNum(String psptNum) { set("psptNum",psptNum);}
	/** get 여권번호 : psptNum */
	public String getPsptNum() { return (String)get("psptNum");}
	/** set 체류시작일자 : styBgnnDt */
	public void setStyBgnnDt(String styBgnnDt) { set("styBgnnDt",styBgnnDt);}
	/** get 체류시작일자 : styBgnnDt */
	public String getStyBgnnDt() { return (String)get("styBgnnDt");}
	/** set 체류종료일자 : styEndDt */
	public void setStyEndDt(String styEndDt) { set("styEndDt",styEndDt);}
	/** get 체류종료일자 : styEndDt */
	public String getStyEndDt() { return (String)get("styEndDt");}
	/** set 최종학교 : endSchl */
	public void setEndSchl(String endSchl) { set("endSchl",endSchl);}
	/** get 최종학교 : endSchl */
	public String getEndSchl() { return (String)get("endSchl");}
	/** set 최종학위구분코드 : endDegrDivCd */
	public void setEndDegrDivCd(String endDegrDivCd) { set("endDegrDivCd",endDegrDivCd);}
	/** get 최종학위구분코드 : endDegrDivCd */
	public String getEndDegrDivCd() { return (String)get("endDegrDivCd");}
	/** set 승진예정일자 : pmtnScduDt */
	public void setPmtnScduDt(String pmtnScduDt) { set("pmtnScduDt",pmtnScduDt);}
	/** get 승진예정일자 : pmtnScduDt */
	public String getPmtnScduDt() { return (String)get("pmtnScduDt");}
	/** set 호봉승급예정일자 : pyspPrmtnScduDt */
	public void setPyspPrmtnScduDt(String pyspPrmtnScduDt) { set("pyspPrmtnScduDt",pyspPrmtnScduDt);}
	/** get 호봉승급예정일자 : pyspPrmtnScduDt */
	public String getPyspPrmtnScduDt() { return (String)get("pyspPrmtnScduDt");}
	/** set 재고용예정일자 : reymnScduDt */
	public void setReymnScduDt(String reymnScduDt) { set("reymnScduDt",reymnScduDt);}
	/** get 재고용예정일자 : reymnScduDt */
	public String getReymnScduDt() { return (String)get("reymnScduDt");}
	/** set 근속년수코드 : logSvcYrNumCd */
	public void setLogSvcYrNumCd(String logSvcYrNumCd) { set("logSvcYrNumCd",logSvcYrNumCd);}
	/** get 근속년수코드 : logSvcYrNumCd */
	public String getLogSvcYrNumCd() { return (String)get("logSvcYrNumCd");}
	/** set 근속월수코드 : logSvcMnthIcmCd */
	public void setLogSvcMnthIcmCd(String logSvcMnthIcmCd) { set("logSvcMnthIcmCd",logSvcMnthIcmCd);}
	/** get 근속월수코드 : logSvcMnthIcmCd */
	public String getLogSvcMnthIcmCd() { return (String)get("logSvcMnthIcmCd");}
	/** set 현_호봉발령일자 : currPyspAppmtDt */
	public void setCurrPyspAppmtDt(String currPyspAppmtDt) { set("currPyspAppmtDt",currPyspAppmtDt);}
	/** get 현_호봉발령일자 : currPyspAppmtDt */
	public String getCurrPyspAppmtDt() { return (String)get("currPyspAppmtDt");}
	/** set 현_부서발령일자 : currDeptAppmtDt */
	public void setCurrDeptAppmtDt(String currDeptAppmtDt) { set("currDeptAppmtDt",currDeptAppmtDt);}
	/** get 현_부서발령일자 : currDeptAppmtDt */
	public String getCurrDeptAppmtDt() { return (String)get("currDeptAppmtDt");}
	/** set 인사비고내용 : pernNoteCtnt */
	public void setPernNoteCtnt(String pernNoteCtnt) { set("pernNoteCtnt",pernNoteCtnt);}
	/** get 인사비고내용 : pernNoteCtnt */
	public String getPernNoteCtnt() { return (String)get("pernNoteCtnt");}
	
	/** set 호봉등급코드 : pyspGrdeCd */
	public void setPyspGrdeCd(String pyspGrdeCd) { set("pyspGrdeCd",pyspGrdeCd);}
	/** get 호봉등급코드 : pyspGrdeCd */
	public String getPyspGrdeCd() { return (String)get("pyspGrdeCd");}
	/** set 직종세구분코드 : dtilOccuClsDivCd */
	public void setDtilOccuClsDivCd(String dtilOccuClsDivCd) { set("dtilOccuClsDivCd",dtilOccuClsDivCd);}
	/** get 직종세구분코드 : dtilOccuClsDivCd */
	public String getDtilOccuClsDivCd() { return (String)get("dtilOccuClsDivCd");}

	/** set 고용일련번호 : emymtSeilNum */
	public void setEmymtSeilNum(String emymtSeilNum) { set("emymtSeilNum",emymtSeilNum);}
	/** get 고용일련번호 : emymtSeilNum */
	public String getEmymtSeilNum() { return (String)get("emymtSeilNum");}
	/** set 고용유형코드 : emymtTypCd */
	public void setEmymtTypCd(String emymtTypCd) { set("emymtTypCd",emymtTypCd);}
	/** get 고용유형코드 : emymtTypCd */
	public String getEmymtTypCd() { return (String)get("emymtTypCd");}
	/** set 현근무지명 : currPaeWorkNm */
	public void setCurrPaeWorkNm(String currPaeWorkNm) { set("currPaeWorkNm",currPaeWorkNm);}
	/** get 현근무지명 : currPaeWorkNm */
	public String getCurrPaeWorkNm() { return (String)get("currPaeWorkNm");}
	/** set 급여지급구분코드 : payPymtDivCd */
	public void setPayPymtDivCd(String payPymtDivCd) { set("payPymtDivCd",payPymtDivCd);}
	/** get 급여지급구분코드 : payPymtDivCd */
	public String getPayPymtDivCd() { return (String)get("payPymtDivCd");}
	/** set 고용금액 : emymtSum */
	public void setEmymtSum(String emymtSum) { set("emymtSum",emymtSum);}
	/** get 고용금액 : emymtSum */
	public String getEmymtSum() { return (String)get("emymtSum");}
	/** set 고용사유내용 : emymtReasCtnt */
	public void setEmymtReasCtnt(String emymtReasCtnt) { set("emymtReasCtnt",emymtReasCtnt);}
	/** get 고용사유내용 : emymtReasCtnt */
	public String getEmymtReasCtnt() { return (String)get("emymtReasCtnt");}
	/** set 증번호 : certNumHuhd */
	public void setCertNumHuhd(String certNumHuhd) { set("certNumHuhd",certNumHuhd);}
	/** get 증번호 : certNumHuhd */
	public String getCertNumHuhd() { return (String)get("certNumHuhd");}
	/** set 경감시작일자 : rducBgnnDt */
	public void setRducBgnnDt(String rducBgnnDt) { set("rducBgnnDt",rducBgnnDt);}
	/** get 경감시작일자 : rducBgnnDt */
	public String getRducBgnnDt() { return (String)get("rducBgnnDt");}
	/** set 경감종료일자 : rducEndDt */
	public void setRducEndDt(String rducEndDt) { set("rducEndDt",rducEndDt);}
	/** get 경감종료일자 : rducEndDt */
	public String getRducEndDt() { return (String)get("rducEndDt");}
	
	/** set 호주성명 : hfmlyNm */
	public void setHfmlyNm(String hfmlyNm) { set("hfmlyNm",hfmlyNm);}
	/** get 호주성명 : hfmlyNm */
	public String getHfmlyNm() { return (String)get("hfmlyNm");}
	/** set 호주와의관계코드 : hfmlyRelaCd */
	public void setHfmlyRelaCd(String hfmlyRelaCd) { set("hfmlyRelaCd",hfmlyRelaCd);}
	/** get 호주와의관계코드 : hfmlyRelaCd */
	public String getHfmlyRelaCd() { return (String)get("hfmlyRelaCd");}
	/** set 출생지주소 : bthcAddr */
	public void setBthcAddr(String bthcAddr) { set("bthcAddr",bthcAddr);}
	/** get 출생지주소 : bthcAddr */
	public String getBthcAddr() { return (String)get("bthcAddr");}
	/** set 집우편번호 : husZpcd */
	public void setHusZpcd(String husZpcd) { set("husZpcd",husZpcd);}
	/** get 집우편번호 : husZpcd */
	public String getHusZpcd() { return (String)get("husZpcd");}
	/** set 집기본주소 : husFndtnAddr */
	public void setHusFndtnAddr(String husFndtnAddr) { set("husFndtnAddr",husFndtnAddr);}
	/** get 집기본주소 : husFndtnAddr */
	public String getHusFndtnAddr() { return (String)get("husFndtnAddr");}
	/** set 집상세주소 : husDtlPatrAddr */
	public void setHusDtlPatrAddr(String husDtlPatrAddr) { set("husDtlPatrAddr",husDtlPatrAddr);}
	/** get 집상세주소 : husDtlPatrAddr */
	public String getHusDtlPatrAddr() { return (String)get("husDtlPatrAddr");}
	/** set 집도로명우편번호 : husRoadNmZpcd */
	public void setHusRoadNmZpcd(String husRoadNmZpcd) { set("husRoadNmZpcd",husRoadNmZpcd);}
	/** get 집도로명우편번호 : husRoadNmZpcd */
	public String getHusRoadNmZpcd() { return (String)get("husRoadNmZpcd");}
	/** set 집도로명기본주소 : husRoadNmFndtnAddr */
	public void setHusRoadNmFndtnAddr(String husRoadNmFndtnAddr) { set("husRoadNmFndtnAddr",husRoadNmFndtnAddr);}
	/** get 집도로명기본주소 : husRoadNmFndtnAddr */
	public String getHusRoadNmFndtnAddr() { return (String)get("husRoadNmFndtnAddr");}
	/** set 집도로명상세주소 : husRoadNmDtlPatrAddr */
	public void setHusRoadNmDtlPatrAddr(String husRoadNmDtlPatrAddr) { set("husRoadNmDtlPatrAddr",husRoadNmDtlPatrAddr);}
	/** get 집도로명상세주소 : husRoadNmDtlPatrAddr */
	public String getHusRoadNmDtlPatrAddr() { return (String)get("husRoadNmDtlPatrAddr");}
	/** set 집전화번호 : husPhnNum */
	public void setHusPhnNum(String husPhnNum) { set("husPhnNum",husPhnNum);}
	/** get 집전화번호 : husPhnNum */
	public String getHusPhnNum() { return (String)get("husPhnNum");}
	/** set 집도로명영문주소 : husRoadNmEngAddr */
	public void setHusRoadNmEngAddr(String husRoadNmEngAddr) { set("husRoadNmEngAddr",husRoadNmEngAddr);}
	/** get 집도로명영문주소 : husRoadNmEngAddr */
	public String getHusRoadNmEngAddr() { return (String)get("husRoadNmEngAddr");}
	/** set 직장우편번호 : wkOfcZpcd */
	public void setWkOfcZpcd(String wkOfcZpcd) { set("wkOfcZpcd",wkOfcZpcd);}
	/** get 직장우편번호 : wkOfcZpcd */
	public String getWkOfcZpcd() { return (String)get("wkOfcZpcd");}
	/** set 직장기본주소 : wkOfcFndtnAddr */
	public void setWkOfcFndtnAddr(String wkOfcFndtnAddr) { set("wkOfcFndtnAddr",wkOfcFndtnAddr);}
	/** get 직장기본주소 : wkOfcFndtnAddr */
	public String getWkOfcFndtnAddr() { return (String)get("wkOfcFndtnAddr");}
	/** set 직장상세주소 : wkOfcDtlPatrAddr */
	public void setWkOfcDtlPatrAddr(String wkOfcDtlPatrAddr) { set("wkOfcDtlPatrAddr",wkOfcDtlPatrAddr);}
	/** get 직장상세주소 : wkOfcDtlPatrAddr */
	public String getWkOfcDtlPatrAddr() { return (String)get("wkOfcDtlPatrAddr");}
	/** set 회사전화번호 : cmpyPhnNum */
	public void setCmpyPhnNum(String cmpyPhnNum) { set("cmpyPhnNum",cmpyPhnNum);}
	/** get 회사전화번호 : cmpyPhnNum */
	public String getCmpyPhnNum() { return (String)get("cmpyPhnNum");}
	/** set 회사팩스번호 : cmpyFaxNum */
	public void setCmpyFaxNum(String cmpyFaxNum) { set("cmpyFaxNum",cmpyFaxNum);}
	/** get 회사팩스번호 : cmpyFaxNum */
	public String getCmpyFaxNum() { return (String)get("cmpyFaxNum");}
	/** set 차량번호 : carNum */
	public void setCarNum(String carNum) { set("carNum",carNum);}
	/** get 차량번호 : carNum */
	public String getCarNum() { return (String)get("carNum");}
	/** set 차종 : carMdl */
	public void setCarMdl(String carMdl) { set("carMdl",carMdl);}
	/** get 차종 : carMdl */
	public String getCarMdl() { return (String)get("carMdl");}
	/** set 핸드폰번호 : cellPhneNum */
	public void setCellPhneNum(String cellPhneNum) { set("cellPhneNum",cellPhneNum);}
	/** get 핸드폰번호 : cellPhneNum */
	public String getCellPhneNum() { return (String)get("cellPhneNum");}
	/** set 이메일주소 : emailAddr */
	public void setEmailAddr(String emailAddr) { set("emailAddr",emailAddr);}
	/** get 이메일주소 : emailAddr */
	public String getEmailAddr() { return (String)get("emailAddr");}
	/** set 증명발급번호 : prfIssNum */
	public void setPrfIssNum(String prfIssNum) { set("prfIssNum",prfIssNum);}
	/** get 증명발급번호 : prfIssNum */
	public String getPrfIssNum() { return (String)get("prfIssNum");}
	/** set 증명서구분코드 : certcDivCd */
	public void setCertcDivCd(String certcDivCd) { set("certcDivCd",certcDivCd);}
	/** get 증명서구분코드 : certcDivCd */
	public String getCertcDivCd() { return (String)get("certcDivCd");}
	/** set 증명서발급일자 : certcIssDt */
	public void setCertcIssDt(String certcIssDt) { set("certcIssDt",certcIssDt);}
	/** get 증명서발급일자 : certcIssDt */
	public String getCertcIssDt() { return (String)get("certcIssDt");}
	/** set 발급부수 : issNumCpis */
	public void setIssNumCpis(String issNumCpis) { set("issNumCpis",issNumCpis);}
	/** get 발급부수 : issNumCpis */
	public String getIssNumCpis() { return (String)get("issNumCpis");}
	/** set 발급용도내용 : issPrpseCtnt */
	public void setIssPrpseCtnt(String issPrpseCtnt) { set("issPrpseCtnt",issPrpseCtnt);}
	/** get 발급용도내용 : issPrpseCtnt */
	public String getIssPrpseCtnt() { return (String)get("issPrpseCtnt");}
	/** set 발급기관명 : issIstutNm */
	public void setIssIstutNm(String issIstutNm) { set("issIstutNm",issIstutNm);}
	/** get 발급기관명 : issIstutNm */
	public String getIssIstutNm() { return (String)get("issIstutNm");}
	/** set 발급신청일자 : issAppyDt */
	public void setIssAppyDt(String issAppyDt) { set("issAppyDt",issAppyDt);}
	/** get 발급신청일자 : issAppyDt */
	public String getIssAppyDt() { return (String)get("issAppyDt");}
	/** set 발급승인일자 : issAppbnDt */
	public void setIssAppbnDt(String issAppbnDt) { set("issAppbnDt",issAppbnDt);}
	/** get 발급승인일자 : issAppbnDt */
	public String getIssAppbnDt() { return (String)get("issAppbnDt");}
	/** set 발급상태구분코드 : issCodtnDivCd */
	public void setIssCodtnDivCd(String issCodtnDivCd) { set("issCodtnDivCd",issCodtnDivCd);}
	/** get 발급상태구분코드 : issCodtnDivCd */
	public String getIssCodtnDivCd() { return (String)get("issCodtnDivCd");}
	/** set 발급승인담당자번호 : issCodtnEmpNum */
	public void setIssCodtnEmpNum(String issCodtnEmpNum) { set("issCodtnEmpNum",issCodtnEmpNum);}
	/** get 발급승인담당자번호 : issCodtnEmpNum */
	public String getIssCodtnEmpNum() { return (String)get("issCodtnEmpNum");}
	/** set 증명서발급여부 : issYn */
	public void setIssYn(String issYn) { set("issYn",issYn);}
	/** get 증명서발급여부 : issYn */
	public String getIssYn() { return (String)get("issYn");}
	/** set 증명서발급삭제여부 : certcIssDelYn */
	public void setCertcIssDelYn(String certcIssDelYn) { set("certcIssDelYn",certcIssDelYn);}
	/** get 증명서발급삭제여부 : certcIssDelYn */
	public String getCertcIssDelYn() { return (String)get("certcIssDelYn");}
	
	
	
	/** set 고용구분코드 : emymtDivCd */
	public void setChildEmymtDivCd(String childEmymtDivCd) { set("childEmymtDivCd",childEmymtDivCd);}
	/** get 고용구분코드 : emymtDivCd */
	public String getChildEmymtDivCd() { return (String)get("childEmymtDivCd");}
	/** set 부서코드 : deptCd */
	public void setChildDeptCd(String childDeptCd) { set("childDeptCd",childDeptCd);}
	/** get 부서코드 : deptCd */
	public String getChildDeptCd() { return (String)get("childDeptCd");}
	/** set 사업코드 : businCd */
	public void setChildBusinCd(String childBusinCd) { set("childBusinCd",childBusinCd);}
	/** get 사업코드 : businCd */
	public String getChildBusinCd() { return (String)get("childBusinCd");}
	/** set 직종코드 : typOccuCd */
	public void setChildTypOccuCd(String childTypOccuCd) { set("childTypOccuCd",childTypOccuCd);}
	/** get 직종코드 : typOccuCd */
	public String getChildTypOccuCd() { return (String)get("childTypOccuCd");}
	/** set 직종세구분코드 : dtilOccuClsDivCd */
	public void setChildDtilOccuClsDivCd(String childDtilOccuClsDivCd) { set("childDtilOccuClsDivCd",childDtilOccuClsDivCd);}
	/** get 직종세구분코드 : dtilOccuClsDivCd */
	public String getChildDtilOccuClsDivCd() { return (String)get("childDtilOccuClsDivCd");}
	
	/** set 주소 : addr */
	public void setAddr(String addr) { set("addr",addr);}
	/** get 주소 : addr */
	public String getAddr() { return (String)get("addr");}
	
	
	public void setSearchIssAppyDtS(String searchIssAppyDtS) { set("searchIssAppyDtS",searchIssAppyDtS);}
	public String getSearchIssAppyDtS() { return (String)get("searchIssAppyDtS");}
	
	public void setSearchIssAppyDtE(String searchIssAppyDtE) { set("searchIssAppyDtE",searchIssAppyDtE);}
	public String getSearchIssAppyDtE() { return (String)get("searchIssAppyDtE");}
	
	public void setConfirmYn(String confirmYn) { set("confirmYn",confirmYn);}
	public String getConfirmYn() { return (String)get("confirmYn");}
	
	
	
	
}
