/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.sysm.server.vo;

  
// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

/**
 * AdmSysm0300Utenti generated by hbm2java
 */
public class SysIfSysm0500VO implements java.io.Serializable {
 

    /** set 시스템구분코드 : sysDivCd */
    private java.lang.String sysDivCd;

    /** set 사용자아이디 : usrId */
    private java.lang.String usrId;

    /** set 사용자권한구분코드 : usrDivCd */
    private java.lang.String usrDivCd;
    
    /** set 사용자권한구분 : usrDivNm */
    private java.lang.String usrDivNm;

    /** set 사용자권한사용여부 : usrAuthUseYn */
    private String usrAuthUseYn;

    /** set 입력자 : kybdr */
    private java.lang.String kybdr;

    /** set 입력일자 : inptDt */
    private java.lang.String inptDt;

    /** set 수정자 : ismt */
    private java.lang.String ismt;

    /** set 수정일자 : revnDt */
    private java.lang.String revnDt;

    /** set 수정주소 : revnAddr */
    private java.lang.String revnAddr;

    /** set 입력주소 : inptAddr */
    private java.lang.String inptAddr; 
    
    /** USR_NM */
    private java.lang.String usrNm;
     
   
    /** AUTH_GRP_SEIL_NUM */
    private Long authGrpSeilNum;
    
    /** set 권한그룹명 : authGrpNm */
    private java.lang.String authGrpNm;
    
    private SysIfSysm0100VO admUser;
    private SysIfSysm0300VO admSysm0300;

    public SysIfSysm0500VO() {
    }

    
    
    /**
	 * Comment : 
	 * @fn Long getAuthGrpSeilNum()
	 * @brief date:2017 2017. 12. 19. user:atres
	 * @return the authGrpSeilNum get
	 */
	public Long getAuthGrpSeilNum() {
		return authGrpSeilNum;
	}



	/**
	 * Comment : 
	 *@fn void setAuthGrpSeilNum(Long authGrpSeilNum)
	 *@brief date:2017 2017. 12. 19. user:atres
	 *@param authGrpSeilNum the authGrpSeilNum to set
	 */
	public void setAuthGrpSeilNum(Long authGrpSeilNum) {
		this.authGrpSeilNum = authGrpSeilNum;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getAuthGrpNm()
	 * @brief date:2017 2017. 12. 19. user:atres
	 * @return the authGrpNm get
	 */
	public java.lang.String getAuthGrpNm() {
		return authGrpNm;
	}



	/**
	 * Comment : 
	 *@fn void setAuthGrpNm(java.lang.String authGrpNm)
	 *@brief date:2017 2017. 12. 19. user:atres
	 *@param authGrpNm the authGrpNm to set
	 */
	public void setAuthGrpNm(java.lang.String authGrpNm) {
		this.authGrpNm = authGrpNm;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getSysDivCd()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the sysDivCd get
	 */
	public java.lang.String getSysDivCd() {
		return sysDivCd;
	}



	/**
	 * Comment : 
	 *@fn void setSysDivCd(java.lang.String sysDivCd)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param sysDivCd the sysDivCd to set
	 */
	public void setSysDivCd(java.lang.String sysDivCd) {
		this.sysDivCd = sysDivCd;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getUsrId()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the usrId get
	 */
	public java.lang.String getUsrId() {
		return usrId;
	}



	/**
	 * Comment : 
	 *@fn void setUsrId(java.lang.String usrId)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param usrId the usrId to set
	 */
	public void setUsrId(java.lang.String usrId) {
		this.usrId = usrId;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getUsrDivCd()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the usrDivCd get
	 */
	public java.lang.String getUsrDivCd() {
		return usrDivCd;
	}



	/**
	 * Comment : 
	 *@fn void setUsrDivCd(java.lang.String usrDivCd)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param usrDivCd the usrDivCd to set
	 */
	public void setUsrDivCd(java.lang.String usrDivCd) {
		this.usrDivCd = usrDivCd;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getUsrDivNm()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the usrDivNm get
	 */
	public java.lang.String getUsrDivNm() {
		return usrDivNm;
	}



	/**
	 * Comment : 
	 *@fn void setUsrDivNm(java.lang.String usrDivNm)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param usrDivNm the usrDivNm to set
	 */
	public void setUsrDivNm(java.lang.String usrDivNm) {
		this.usrDivNm = usrDivNm;
	}



	/**
	 * Comment : 
	 * @fn Boolean getUsrAuthUseYn()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the usrAuthUseYn get
	 */
	public String getUsrAuthUseYn() {
		return usrAuthUseYn;
	}



	/**
	 * Comment : 
	 *@fn void setUsrAuthUseYn(Boolean usrAuthUseYn)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param usrAuthUseYn the usrAuthUseYn to set
	 */
	public void setUsrAuthUseYn(String usrAuthUseYn) {
		this.usrAuthUseYn = usrAuthUseYn;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getKybdr()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the kybdr get
	 */
	public java.lang.String getKybdr() {
		return kybdr;
	}



	/**
	 * Comment : 
	 *@fn void setKybdr(java.lang.String kybdr)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param kybdr the kybdr to set
	 */
	public void setKybdr(java.lang.String kybdr) {
		this.kybdr = kybdr;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getInptDt()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the inptDt get
	 */
	public java.lang.String getInptDt() {
		return inptDt;
	}



	/**
	 * Comment : 
	 *@fn void setInptDt(java.lang.String inptDt)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param inptDt the inptDt to set
	 */
	public void setInptDt(java.lang.String inptDt) {
		this.inptDt = inptDt;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getIsmt()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the ismt get
	 */
	public java.lang.String getIsmt() {
		return ismt;
	}



	/**
	 * Comment : 
	 *@fn void setIsmt(java.lang.String ismt)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param ismt the ismt to set
	 */
	public void setIsmt(java.lang.String ismt) {
		this.ismt = ismt;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getRevnDt()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the revnDt get
	 */
	public java.lang.String getRevnDt() {
		return revnDt;
	}



	/**
	 * Comment : 
	 *@fn void setRevnDt(java.lang.String revnDt)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param revnDt the revnDt to set
	 */
	public void setRevnDt(java.lang.String revnDt) {
		this.revnDt = revnDt;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getRevnAddr()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the revnAddr get
	 */
	public java.lang.String getRevnAddr() {
		return revnAddr;
	}



	/**
	 * Comment : 
	 *@fn void setRevnAddr(java.lang.String revnAddr)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param revnAddr the revnAddr to set
	 */
	public void setRevnAddr(java.lang.String revnAddr) {
		this.revnAddr = revnAddr;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getInptAddr()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the inptAddr get
	 */
	public java.lang.String getInptAddr() {
		return inptAddr;
	}



	/**
	 * Comment : 
	 *@fn void setInptAddr(java.lang.String inptAddr)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param inptAddr the inptAddr to set
	 */
	public void setInptAddr(java.lang.String inptAddr) {
		this.inptAddr = inptAddr;
	}



	/**
	 * Comment : 
	 * @fn java.lang.String getUsrNm()
	 * @brief date:2017 2017. 11. 7. user:atres
	 * @return the usrNm get
	 */
	public java.lang.String getUsrNm() {
		return usrNm;
	}



	/**
	 * Comment : 
	 *@fn void setUsrNm(java.lang.String usrNm)
	 *@brief date:2017 2017. 11. 7. user:atres
	 *@param usrNm the usrNm to set
	 */
	public void setUsrNm(java.lang.String usrNm) {
		this.usrNm = usrNm;
	}



	public SysIfSysm0500VO(SysIfSysm0100VO admUser, SysIfSysm0300VO admSysm0300) {
        this.admUser = admUser;
        this.admSysm0300 = admSysm0300;
    }
    
    

    public SysIfSysm0100VO getAdmUser() {
        return this.admUser;
    }

    public void setAdmUser(SysIfSysm0100VO admUser) {
        this.admUser = admUser;
    }

    public SysIfSysm0300VO getAdmSysm0300() {
        return this.admSysm0300;
    }

    public void setAdmSysm0300(SysIfSysm0300VO admSysm0300) {
        this.admSysm0300 = admSysm0300;
    }

}
