/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.sysm.server.vo;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

 
import java.util.HashSet;
import java.util.Set;

/**
 * AdmMenu generated by hbm2java
 */
public class SysIfSysm0200VO implements java.io.Serializable {

  
    private SysIfSysm0200VO admMenu;
    
    
    /** RowCnt */
    private long RowCnt;
    
    /** SYS_DIV_CD */
    private java.lang.String sysDivCd;
    
    /** MNU_CD */
    private java.lang.String mnuCd;
    
    /** HHRK_MNU_CD */
    private java.lang.String hhrkMnuCd;
    
    /** MNU_NM */
    private java.lang.String mnuNm;
    
    /** MNU_ICN */
    private java.lang.String mnuIcn;
    
    /** MNU_TMBL */
    private java.lang.String mnuTmbl;
    
    /** MNU_AUTH_FRM_CD */
    private java.lang.String mnuAuthFrmCd;
    
    /** MNU_TIP_NM */
    private java.lang.String mnuTipNm;
    
    /** MNU_SCN_FRM_PKG_NM */
    private java.lang.String mnuScnFrmPkgNm;
    
    /** MNU_PRNT_YN */
    private java.lang.String mnuPrntYn;
    
    /** MNU_PRNT_ORD */
    private Long mnuPrntOrd;
    
    /** USE_YN */
    private java.lang.String useYn;
    
    /** MNU_EPLN */
    private java.lang.String mnuEpln;
    
    /** KYBDR */
    private java.lang.String kybdr;
    
    /** INPT_DT */
    private java.lang.String inptDt;
    
    /** ISMT */
    private java.lang.String ismt;
    
    /** REVN_DT */
    private java.lang.String revnDt;
    
    /** REVN_ADDR */
    private java.lang.String revnAddr;
    
    /** INPT_ADDR */
    private java.lang.String inptAddr;
    

    /** MNU_AUTH_GR_P_SCN_INQY_YN */
    private java.lang.String mnuAuthGrPScnInqyYn;
    
    /** MNU_AUTH_GR_P_SCN_INPT_YN */
    private java.lang.String mnuAuthGrPScnInptYn;
    
    /** MNU_AUTH_GR_P_SCN_REVN_YN */
    private java.lang.String mnuAuthGrPScnRevnYn;
    
    /** MNU_AUTH_GR_P_SCN_DEL_YN */
    private java.lang.String mnuAuthGrPScnDelYn;
    
    /** MNU_AUTH_GR_P_SCN_PRT_YN */
    private java.lang.String mnuAuthGrPScnPrtYn;
    
    
    private Set admMenuSysm0400 = new HashSet(0);
 //   private Set admMenusSysm0200 = new HashSet(0);
 //   private Set admMenuSysm0500 = new HashSet(0);
 

    public SysIfSysm0200VO() {
    }

    public SysIfSysm0200VO(SysIfSysm0200VO admMenu
    		,String sysDivCd
    		,String mnuCd
    		,String hhrkMnuCd 
    		,String mnuNm              
    		,String mnuIcn             
    		,String mnuTmbl            
    		,String mnuAuthFrmCd       
    		,String mnuTipNm           
    		,String mnuScnFrmPkgNm     
    		,String mnuPrntYn          
    		,Long mnuPrntOrd         
    		,String useYn              
    		,String mnuEpln       
    		,Set admMenuSysm0400
    	//	, Set admMenusSysm0200
    //		, Set admMenuSysm0500
             ) {
        this.admMenu = admMenu;
    	this.sysDivCd            =  sysDivCd;
    	this.mnuCd               =  mnuCd;
    	this.hhrkMnuCd           =  hhrkMnuCd;
    	this.mnuNm               =  mnuNm;                    
    	this.mnuIcn              =  mnuIcn;              
    	this.mnuTmbl             =  mnuTmbl;             
    	this.mnuAuthFrmCd        =  mnuAuthFrmCd;        
    	this.mnuTipNm            =  mnuTipNm;            
    	this.mnuScnFrmPkgNm      =  mnuScnFrmPkgNm;      
    	this.mnuPrntYn           =  mnuPrntYn;           
    	this.mnuPrntOrd          =  mnuPrntOrd;          
    	this.useYn               =  useYn;               
    	this.mnuEpln             =  mnuEpln;             
        this.admMenuSysm0400 = admMenuSysm0400;
     //   this.admMenusSysm0200 = admMenusSysm0200;
     //   this.admMenuSysm0500 = admMenuSysm0500;
    }
 

    public SysIfSysm0200VO getAdmMenu() {
        return this.admMenu;
    }

    public void setAdmMenu(SysIfSysm0200VO admMenu) {
        this.admMenu = admMenu;
    }
    
    
    public long getRowCnt() {
        return RowCnt;
    }

    public void setRowCnt(long rowCnt) {
        RowCnt = rowCnt;
    }

    public java.lang.String getSysDivCd() {
        return this.sysDivCd;
    }
    
    public void setSysDivCd(java.lang.String sysDivCd) {
        this.sysDivCd = sysDivCd;
    }
    
    public java.lang.String getMnuCd() {
        return this.mnuCd;
    }
    
    public void setMnuCd(java.lang.String mnuCd) {
        this.mnuCd = mnuCd;
    }
    
    public java.lang.String getHhrkMnuCd() {
        return this.hhrkMnuCd;
    }
    
    public void setHhrkMnuCd(java.lang.String hhrkMnuCd) {
        this.hhrkMnuCd = hhrkMnuCd;
    }
    
    public java.lang.String getMnuNm() {
        return this.mnuNm;
    }
    
    public void setMnuNm(java.lang.String mnuNm) {
        this.mnuNm = mnuNm;
    }
    
    public java.lang.String getMnuIcn() {
        return this.mnuIcn;
    }
    
    public void setMnuIcn(java.lang.String mnuIcn) {
        this.mnuIcn = mnuIcn;
    }
    
    public java.lang.String getMnuTmbl() {
        return this.mnuTmbl;
    }
    
    public void setMnuTmbl(java.lang.String mnuTmbl) {
        this.mnuTmbl = mnuTmbl;
    }
    
    public java.lang.String getMnuAuthFrmCd() {
        return this.mnuAuthFrmCd;
    }
    
    public void setMnuAuthFrmCd(java.lang.String mnuAuthFrmCd) {
        this.mnuAuthFrmCd = mnuAuthFrmCd;
    }
    
    public java.lang.String getMnuTipNm() {
        return this.mnuTipNm;
    }
    
    public void setMnuTipNm(java.lang.String mnuTipNm) {
        this.mnuTipNm = mnuTipNm;
    }
    
    public java.lang.String getMnuScnFrmPkgNm() {
        return this.mnuScnFrmPkgNm;
    }
    
    public void setMnuScnFrmPkgNm(java.lang.String mnuScnFrmPkgNm) {
        this.mnuScnFrmPkgNm = mnuScnFrmPkgNm;
    }
    
    public java.lang.String getMnuPrntYn() {
        return this.mnuPrntYn;
    }
    
    public void setMnuPrntYn(java.lang.String mnuPrntYn) {
        this.mnuPrntYn = mnuPrntYn;
    }
    
    public Long getMnuPrntOrd() {
        return this.mnuPrntOrd;
    }
    
    public void setMnuPrntOrd(Long mnuPrntOrd) {
        this.mnuPrntOrd = mnuPrntOrd;
    }
    
    public java.lang.String getUseYn() {
        return this.useYn;
    }
    
    public void setUseYn(java.lang.String useYn) {
        this.useYn = useYn;
    }
    
    public java.lang.String getMnuEpln() {
        return this.mnuEpln;
    }
    
    public void setMnuEpln(java.lang.String mnuEpln) {
        this.mnuEpln = mnuEpln;
    }
    
    public java.lang.String getKybdr() {
        return this.kybdr;
    }
    
    public void setKybdr(java.lang.String kybdr) {
        this.kybdr = kybdr;
    }
    
    public java.lang.String getInptDt() {
        return this.inptDt;
    }
    
    public void setInptDt(java.lang.String inptDt) {
        this.inptDt = inptDt;
    }
    
    public java.lang.String getIsmt() {
        return this.ismt;
    }
    
    public void setIsmt(java.lang.String ismt) {
        this.ismt = ismt;
    }
    
    public java.lang.String getRevnDt() {
        return this.revnDt;
    }
    
    public void setRevnDt(java.lang.String revnDt) {
        this.revnDt = revnDt;
    }
    
    public java.lang.String getRevnAddr() {
        return this.revnAddr;
    }
    
    public void setRevnAddr(java.lang.String revnAddr) {
        this.revnAddr = revnAddr;
    }
    
    public java.lang.String getInptAddr() {
        return this.inptAddr;
    }
    
    public void setInptAddr(java.lang.String inptAddr) {
        this.inptAddr = inptAddr;
    }
 
    public Set getAdmMenuSysm0400() {
        return this.admMenuSysm0400;
    }

    public void setAdmMenuSysm0400(Set admMenuSysm0400) {
        this.admMenuSysm0400 = admMenuSysm0400;
    }

	public java.lang.String getMnuAuthGrPScnInqyYn() {
		return mnuAuthGrPScnInqyYn;
	}

	public void setMnuAuthGrPScnInqyYn(java.lang.String mnuAuthGrPScnInqyYn) {
		this.mnuAuthGrPScnInqyYn = mnuAuthGrPScnInqyYn;
	}

	public java.lang.String getMnuAuthGrPScnInptYn() {
		return mnuAuthGrPScnInptYn;
	}

	public void setMnuAuthGrPScnInptYn(java.lang.String mnuAuthGrPScnInptYn) {
		this.mnuAuthGrPScnInptYn = mnuAuthGrPScnInptYn;
	}

	public java.lang.String getMnuAuthGrPScnRevnYn() {
		return mnuAuthGrPScnRevnYn;
	}

	public void setMnuAuthGrPScnRevnYn(java.lang.String mnuAuthGrPScnRevnYn) {
		this.mnuAuthGrPScnRevnYn = mnuAuthGrPScnRevnYn;
	}

	public java.lang.String getMnuAuthGrPScnDelYn() {
		return mnuAuthGrPScnDelYn;
	}

	public void setMnuAuthGrPScnDelYn(java.lang.String mnuAuthGrPScnDelYn) {
		this.mnuAuthGrPScnDelYn = mnuAuthGrPScnDelYn;
	}

	public java.lang.String getMnuAuthGrPScnPrtYn() {
		return mnuAuthGrPScnPrtYn;
	}

	public void setMnuAuthGrPScnPrtYn(java.lang.String mnuAuthGrPScnPrtYn) {
		this.mnuAuthGrPScnPrtYn = mnuAuthGrPScnPrtYn;
	}

//    public Set getAdmMenusSysm0200() {
//        return this.admMenusSysm0200;
//    }
//
//    public void setAdmMenusSysm0200(Set admMenusSysm0200) {
//        this.admMenusSysm0200 = admMenusSysm0200;
//    }
//
//    public Set getAdmMenuSysm0500() {
//        return this.admMenuSysm0500;
//    }
//
//    public void setAdmMenuSysm0500(Set admMenuSysm0500) {
//        this.admMenuSysm0500 = admMenuSysm0500;
//    }
    
    

}
