/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.sysm.server.vo;

// Generated 3-mar-2011 10.09.19 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * AdmProfiles generated by hbm2java
 */
public class SysIfSysm0300VO implements java.io.Serializable {


    /** set 시스템구분코드 : sysDivCd */
    private java.lang.String sysDivCd;

    /** set 권한그룹일련번호 : authGrpSeilNum */
    private Long authGrpSeilNum;

    /** set 시스템업무구분코드 : businDivCd */
    private java.lang.String businDivCd;

    /** set 권한그룹명 : authGrpNm */
    private java.lang.String authGrpNm;

    /** set 등급 : grde */
    private java.lang.String grde;

    /** set 권한그룹사용여부 : authGrpUseYn */
    private java.lang.String authGrpUseYn;

    /** set 그룹설명 : grpEpln */
    private java.lang.String grpEpln;

    /** set 입력자 : kybdr */
    private java.lang.String kybdr;

    /** set 입력일자 : inptDt */
    private java.lang.String inptDt;

    /** set 수정자 : ismt */
    private java.lang.String ismt;

    /** set 수정일자 : revnDt */
    private java.lang.String revnDt;

    /** set 수정주소 : revnAddr */
    private java.lang.String revnAddr;

    /** set 입력주소 : inptAddr */
    private java.lang.String inptAddr;

     
     
    private Set admProfilesUsers = new HashSet(0);
    private Set admMenuProfiless = new HashSet(0);

    public SysIfSysm0300VO() {
    }

    public SysIfSysm0300VO(String businDivCd
    		          , String authGrpNm
    		          , String grde
    		          , String authGrpUseYn
    		          , String grpEpln) {
        this.businDivCd = businDivCd;
        this.authGrpNm = authGrpNm;
        this.grde = grde;
        this.authGrpUseYn = authGrpUseYn;
        this.grpEpln = grpEpln;
    }
      

    public SysIfSysm0300VO(String businDivCd
			          , String authGrpNm
			          , String grde
			          , String authGrpUseYn
			          , String grpEpln, Set admProfilesUsers, Set admMenuProfiless) {
    	 this.businDivCd = businDivCd;
         this.authGrpNm = authGrpNm;
         this.grde = grde;
         this.authGrpUseYn = authGrpUseYn;
         this.grpEpln = grpEpln;
         this.admProfilesUsers = admProfilesUsers;
         this.admMenuProfiless = admMenuProfiless;
    }

    
    public java.lang.String getSysDivCd() {
        return this.sysDivCd;
    }
    
    public void setSysDivCd(java.lang.String sysDivCd) {
        this.sysDivCd = sysDivCd;
    }
    
    public Long getAuthGrpSeilNum() {
        return this.authGrpSeilNum;
    }
    
    public void setAuthGrpSeilNum(Long authGrpSeilNum) {
        this.authGrpSeilNum = authGrpSeilNum;
    }
    
    public java.lang.String getBusinDivCd() {
        return this.businDivCd;
    }
    
    public void setBusinDivCd(java.lang.String businDivCd) {
        this.businDivCd = businDivCd;
    }
    
    public java.lang.String getAuthGrpNm() {
        return this.authGrpNm;
    }
    
    public void setAuthGrpNm(java.lang.String authGrpNm) {
        this.authGrpNm = authGrpNm;
    }
    
    public java.lang.String getGrde() {
        return this.grde;
    }
    
    public void setGrde(java.lang.String grde) {
        this.grde = grde;
    }
    
    public java.lang.String getAuthGrpUseYn() {
        return this.authGrpUseYn;
    }
    
    public void setAuthGrpUseYn(java.lang.String authGrpUseYn) {
        this.authGrpUseYn = authGrpUseYn;
    }
    
    public java.lang.String getGrpEpln() {
        return this.grpEpln;
    }
    
    public void setGrpEpln(java.lang.String grpEpln) {
        this.grpEpln = grpEpln;
    }
    
    public java.lang.String getKybdr() {
        return this.kybdr;
    }
    
    public void setKybdr(java.lang.String kybdr) {
        this.kybdr = kybdr;
    }
     
    
    public java.lang.String getIsmt() {
        return this.ismt;
    }
    
    public void setIsmt(java.lang.String ismt) {
        this.ismt = ismt;
    }
     
    public java.lang.String getRevnAddr() {
        return this.revnAddr;
    }
    
    public void setRevnAddr(java.lang.String revnAddr) {
        this.revnAddr = revnAddr;
    }
    
    public java.lang.String getInptAddr() {
        return this.inptAddr;
    }
    
    public void setInptAddr(java.lang.String inptAddr) {
        this.inptAddr = inptAddr;
    }
     
    public Set getAdmProfilesUsers() {
        return this.admProfilesUsers;
    }

    public void setAdmProfilesUsers(Set admProfilesUsers) {
        this.admProfilesUsers = admProfilesUsers;
    }

    public Set getAdmMenuProfiless() {
        return this.admMenuProfiless;
    }

    public void setAdmMenuProfiless(Set admMenuProfiless) {
        this.admMenuProfiless = admMenuProfiless;
    }

	public java.lang.String getInptDt() {
		return inptDt;
	}

	public void setInptDt(java.lang.String inptDt) {
		this.inptDt = inptDt;
	}

	public java.lang.String getRevnDt() {
		return revnDt;
	}

	public void setRevnDt(java.lang.String revnDt) {
		this.revnDt = revnDt;
	}
    
    

}
