/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.sysm.server.vo;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmUtenti generated by hbm2java
 */
public class SysIfSysm0100VO implements  Serializable {

	private static final long serialVersionUID = 1L; // serialVersionUID 추가_hieju/06.14

	/** set 시스템구분코드 : sysDivCd */
	private java.lang.String sysDivCd;
	
	//#sso 사용여부 확인을 위한 설정값  SSOX, NONE 설정 
    private java.lang.String  ssoUseType ;

	/** set 사용자아이디 : usrId */
	private java.lang.String usrId;

	/** set 사용자성명 : usrNm */
	private java.lang.String usrNm;

	/** set 사용자구분코드 : usrDivCd */
	private java.lang.String usrDivCd;

	/** set SYSTEMKEY : systemkey */
	private java.lang.String systemkey;

	/** set 부서코드 : deptCd */
	private java.lang.String deptCd;

	/** set null : usrTel */
	private java.lang.String usrTel;

	/** set 이메일 : email */
	private java.lang.String email;

	/** set 패스워드 : pwd */
	private java.lang.String pwd;
	
	/** set 로그인 횟수 : logincnt */
	private java.lang.String logincnt; // 로그인 횟수 추가
	
	/** set 계정잠금여부 : lockat */
	 private java.lang.String lockat; // 계정잠금여부 추가
	
	/** set 비밀번호 변경 날짜 : pwddate */
	private java.lang.String pwddate; // 비밀번호 변경날짜 추가
	
	/** set 사용자사용여부 : useYn */
	private java.lang.String useYn;

	/** set 입력자 : kybdr */
	private java.lang.String kybdr;

	/** set 입력일자 : inptDt */
	private java.lang.String inptDt;

	/** set 입력주소 : inptAddr */
	private java.lang.String inptAddr;

	/** set 수정자 : ismt */
	private java.lang.String ismt;

	/** set 수정일자 : revnDt */
	private java.lang.String revnDt;

	/** set 수정주소 : revnAddr */
	private java.lang.String revnAddr;

	/** set 직종코드 : typOccuCd */
	private java.lang.String typOccuCd;

	/** set 호봉등급코드 : pyspGrdeCd */
	private java.lang.String pyspGrdeCd;

/** set 직종세통합코드 : dtilOccuInttnCd */
    private java.lang.String dtilOccuInttnCd;

	/** set 사용자권한제외여부 : usrAuthEepnYn */
	private java.lang.String usrAuthEepnYn;

	/** set 호봉제포함여부 : pyspInsnYn */
	private java.lang.String pyspInsnYn;

	/** set 비호봉제포함여부 : notPyspInsnYn */
	private java.lang.String notPyspInsnYn;

	/** set 복무입력처리여부 : servcInptPrcsYn */
	private java.lang.String servcInptPrcsYn;

	/** set 연말정산입력처리여부 : yrtxInptPrcsYn */
	private java.lang.String yrtxInptPrcsYn;

	/** set 기간제포함여부 : shttmInsnYn */
	private java.lang.String shttmInsnYn;

	/** set 사용자권한구분코드 : usrAuthDivCd */
	private java.lang.String usrAuthDivCd;

 
	
	/** set 패스워드 : tmpPwd */
	private java.lang.String tmpPwd;

  
    
	 /** set 사업장코드 - DPOB_CD */
    private java.lang.String dpobCd;
 
    /** set 시스템구분코드 : sysDivNm */
    private java.lang.String sysDivNm;

   
    /** set 사용자구분 : usrDivNm*/
    private java.lang.String usrDivNm;

    

    /** set 부서코드 : deptNm */
    private java.lang.String deptNm;
    
    
    
    /** set 단위기관코드 : payrMangDeptCd */
    private java.lang.String payrMangDeptCd;
    
    /** set 단위기관코드 : payrMangDeptNm */
    private java.lang.String payrMangDeptNm;
    
    /** set 관리부서코드 : mangeDeptCd */
    private java.lang.String mangeDeptCd; 

    /** set 관리부서 : mangeDeptNm */
    private java.lang.String mangeDeptNm;
      
    /** set 최상위부서코드 : tplvlDeptCd */
    private java.lang.String tplvlDeptCd;
    
    /** set 최상위부서코드 : tplvlDeptNm */
    private java.lang.String tplvlDeptNm;
     
    /** set 직종 : typOccuNm TODO 삭제 */
    private java.lang.String typOccuNm;
     
    /** set 등급 : pyspGrdeNm TODO 삭제 */
    private java.lang.String pyspGrdeNm;

    /** set 단위기관담당자여부 : payrMangDeptYn   */
    private java.lang.String payrMangDeptYn;
    
  
    /** AUTH_IN_STDT */
    private java.lang.String authInStdt;
    
    /** AUTH_IN_EDDT */
    private java.lang.String authInEddt;
    
    /** USR_LGN_CNT_CHK */
    private java.math.BigDecimal usrLgnCntChk;
    
    /** USR_LGN_SESSN */
    private java.lang.String usrLgnSessn;
    
    /** USR_LGN_DTTM */
    private java.lang.String usrLgnDttm;
    
    /** USR_LGN_ACC_LCK_YN */
    private java.lang.String usrLgnAccLckYn;
    
    /** UNT_DPOB_CD */
    private java.lang.String untDpobCd;
    
    /** PAY_MANGE_DEPT_CD */
    private java.lang.String payMangeDeptCd;
    
  //private Set admMenuUsers = new HashSet(0);
    private Set admTraceUsers = new HashSet(0);
    private Set admDataHistories = new HashSet(0);
    private Set admSysm0500 = new HashSet(0); 
    private Set admSsoxUser = new HashSet(0); 
    private Set admUserInfo = new HashSet(0); 
    private Set admAuthCheckInfo = new HashSet(0); 
    
    public SysIfSysm0100VO() {
    	
    } 

    public SysIfSysm0100VO(String dpobCd, String sysDivCd, String usrId, String usrNm,String usrDivCd,String deptCd,  
    		String usrTel  , String email, String pwd, String useYn,String tplvlDeptCd, String tplvlDeptNm,
    		String payrMangDeptCd,String mangeDeptCd,String payrMangDeptYn, String yrtxInptPrcsYn ,Set admMenuUsers 
    		, Set admDataHistories, Set admSysm0500, Set admSsoxUser, Set admUserInfo,Set admAuthCheckInfo,
    		String lockat,String logincnt, String pwddate, String inptDt) {
    	this.dpobCd = dpobCd;
    	this.sysDivCd = sysDivCd;
        this.usrId = usrId;
        this.usrNm = usrNm; 
        this.usrDivCd = usrDivCd;
        this.deptCd = deptCd;
     //   this.typOccuCd = typOccuCd;
     //   this.pyspGrdeCd = pyspGrdeCd;
        this.usrTel = usrTel;
        this.email = email;
        this.pwd = pwd;
        this.useYn = useYn;
        this.tplvlDeptCd = tplvlDeptCd;
        this.tplvlDeptNm = tplvlDeptNm;
        this.payrMangDeptCd = payrMangDeptCd;
        this.mangeDeptCd = mangeDeptCd;
        this.payrMangDeptYn = payrMangDeptYn; 
        this.yrtxInptPrcsYn = yrtxInptPrcsYn; 
    //    this.admMenuUsers = admMenuUsers;
        this.admTraceUsers = admTraceUsers;
        this.admDataHistories = admDataHistories;
        this.admSysm0500 = admSysm0500;
        this.admSsoxUser = admSsoxUser;
        this.admUserInfo = admUserInfo;
        this.admAuthCheckInfo = admAuthCheckInfo;
        this.lockat = lockat;
        this.logincnt = logincnt;
        this.pwddate = pwddate;
        this.inptDt = inptDt;
        
        
    }
      
   
	/**
	 * Comment : 
	 * @fn java.lang.String getUsrAuthEepnYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the usrAuthEepnYn get
	 */
	public java.lang.String getUsrAuthEepnYn() {
		return usrAuthEepnYn;
	}

	/**
	 * Comment : 
	 *@fn void setUsrAuthEepnYn(java.lang.String usrAuthEepnYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param usrAuthEepnYn the usrAuthEepnYn to set
	 */
	public void setUsrAuthEepnYn(java.lang.String usrAuthEepnYn) {
		this.usrAuthEepnYn = usrAuthEepnYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getPyspInsnYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the pyspInsnYn get
	 */
	public java.lang.String getPyspInsnYn() {
		return pyspInsnYn;
	}

	/**
	 * Comment : 
	 *@fn void setPyspInsnYn(java.lang.String pyspInsnYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param pyspInsnYn the pyspInsnYn to set
	 */
	public void setPyspInsnYn(java.lang.String pyspInsnYn) {
		this.pyspInsnYn = pyspInsnYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getNotPyspInsnYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the notPyspInsnYn get
	 */
	public java.lang.String getNotPyspInsnYn() {
		return notPyspInsnYn;
	}

	/**
	 * Comment : 
	 *@fn void setNotPyspInsnYn(java.lang.String notPyspInsnYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param notPyspInsnYn the notPyspInsnYn to set
	 */
	public void setNotPyspInsnYn(java.lang.String notPyspInsnYn) {
		this.notPyspInsnYn = notPyspInsnYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getServcInptPrcsYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the servcInptPrcsYn get
	 */
	public java.lang.String getServcInptPrcsYn() {
		return servcInptPrcsYn;
	}

	/**
	 * Comment : 
	 *@fn void setServcInptPrcsYn(java.lang.String servcInptPrcsYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param servcInptPrcsYn the servcInptPrcsYn to set
	 */
	public void setServcInptPrcsYn(java.lang.String servcInptPrcsYn) {
		this.servcInptPrcsYn = servcInptPrcsYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getYrtxInptPrcsYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the yrtxInptPrcsYn get
	 */
	public java.lang.String getYrtxInptPrcsYn() {
		return yrtxInptPrcsYn;
	}

	/**
	 * Comment : 
	 *@fn void setYrtxInptPrcsYn(java.lang.String yrtxInptPrcsYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param yrtxInptPrcsYn the yrtxInptPrcsYn to set
	 */
	public void setYrtxInptPrcsYn(java.lang.String yrtxInptPrcsYn) {
		this.yrtxInptPrcsYn = yrtxInptPrcsYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getShttmInsnYn()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the shttmInsnYn get
	 */
	public java.lang.String getShttmInsnYn() {
		return shttmInsnYn;
	}

	/**
	 * Comment : 
	 *@fn void setShttmInsnYn(java.lang.String shttmInsnYn)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param shttmInsnYn the shttmInsnYn to set
	 */
	public void setShttmInsnYn(java.lang.String shttmInsnYn) {
		this.shttmInsnYn = shttmInsnYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getUsrAuthDivCd()
	 * @brief date:2017 2017. 1. 20. user:atres-pc
	 * @return the usrAuthDivCd get
	 */
	public java.lang.String getUsrAuthDivCd() {
		return usrAuthDivCd;
	}

	/**
	 * Comment : 
	 *@fn void setUsrAuthDivCd(java.lang.String usrAuthDivCd)
	 *@brief date:2017 2017. 1. 20. user:atres-pc
	 *@param usrAuthDivCd the usrAuthDivCd to set
	 */
	public void setUsrAuthDivCd(java.lang.String usrAuthDivCd) {
		this.usrAuthDivCd = usrAuthDivCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getTypOccuCd()
	 * @brief date:2015 Dec 25, 2015 user:leeheuisung
	 * @return the typOccuCd get
	 */
	public java.lang.String getTypOccuCd() {
		return typOccuCd;
	}

	/**
	 * Comment : 
	 *@fn void setTypOccuCd(java.lang.String typOccuCd)
	 *@brief date:2015 Dec 25, 2015 user:leeheuisung
	 *@param typOccuCd the typOccuCd to set
	 */
	public void setTypOccuCd(java.lang.String typOccuCd) {
		this.typOccuCd = typOccuCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getTypOccuNm()
	 * @brief date:2015 Dec 25, 2015 user:leeheuisung
	 * @return the typOccuNm get
	 */
	public java.lang.String getTypOccuNm() {
		return typOccuNm;
	}

	/**
	 * Comment : 
	 *@fn void setTypOccuNm(java.lang.String typOccuNm)
	 *@brief date:2015 Dec 25, 2015 user:leeheuisung
	 *@param typOccuNm the typOccuNm to set
	 */
	public void setTypOccuNm(java.lang.String typOccuNm) {
		this.typOccuNm = typOccuNm;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getPyspGrdeCd()
	 * @brief date:2015 Dec 25, 2015 user:leeheuisung
	 * @return the pyspGrdeCd get
	 */
	public java.lang.String getPyspGrdeCd() {
		return pyspGrdeCd;
	}

	/**
	 * Comment : 
	 *@fn void setPyspGrdeCd(java.lang.String pyspGrdeCd)
	 *@brief date:2015 Dec 25, 2015 user:leeheuisung
	 *@param pyspGrdeCd the pyspGrdeCd to set
	 */
	public void setPyspGrdeCd(java.lang.String pyspGrdeCd) {
		this.pyspGrdeCd = pyspGrdeCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getPyspGrdeNm()
	 * @brief date:2015 Dec 25, 2015 user:leeheuisung
	 * @return the pyspGrdeNm get
	 */
	public java.lang.String getPyspGrdeNm() {
		return pyspGrdeNm;
	}

	/**
	 * Comment : 
	 *@fn void setPyspGrdeNm(java.lang.String pyspGrdeNm)
	 *@brief date:2015 Dec 25, 2015 user:leeheuisung
	 *@param pyspGrdeNm the pyspGrdeNm to set
	 */
	public void setPyspGrdeNm(java.lang.String pyspGrdeNm) {
		this.pyspGrdeNm = pyspGrdeNm;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getTplvlDeptCd()
	 * @brief date:2015 Nov 13, 2015 user:leeheuisung
	 * @return the tplvlDeptCd get
	 */
	public java.lang.String getTplvlDeptCd() {
		return tplvlDeptCd;
	}

	/**
	 * Comment : 
	 *@fn void setTplvlDeptCd(java.lang.String tplvlDeptCd)
	 *@brief date:2015 Nov 13, 2015 user:leeheuisung
	 *@param tplvlDeptCd the tplvlDeptCd to set
	 */
	public void setTplvlDeptCd(java.lang.String tplvlDeptCd) {
		this.tplvlDeptCd = tplvlDeptCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getTplvlDeptNm()
	 * @brief date:2015 Nov 13, 2015 user:leeheuisung
	 * @return the tplvlDeptNm get
	 */
	public java.lang.String getTplvlDeptNm() {
		return tplvlDeptNm;
	}

	public void setTplvlDeptNm(java.lang.String tplvlDeptNm) {
		this.tplvlDeptNm = tplvlDeptNm;
	}

	public java.lang.String getPayrMangDeptYn() {
        return payrMangDeptYn;
    }

    public void setPayrMangDeptYn(java.lang.String payrMangDeptYn) {
        this.payrMangDeptYn = payrMangDeptYn;
    }

    public java.lang.String getSysDivNm() {
        return sysDivNm;
    }

    public void setSysDivNm(java.lang.String sysDivNm) {
        this.sysDivNm = sysDivNm;
    }

    public java.lang.String getUsrDivNm() {
        return usrDivNm;
    }

    public void setUsrDivNm(java.lang.String usrDivNm) {
        this.usrDivNm = usrDivNm;
    }

    public java.lang.String getDeptNm() {
        return deptNm;
    }

    public void setDeptNm(java.lang.String deptNm) {
        this.deptNm = deptNm;
    }

    public java.lang.String getPayrMangDeptNm() {
        return payrMangDeptNm;
    }

    public void setPayrMangDeptNm(java.lang.String payrMangDeptNm) {
        this.payrMangDeptNm = payrMangDeptNm;
    }

    public java.lang.String getMangeDeptNm() {
        return mangeDeptNm;
    }

    public void setMangeDeptNm(java.lang.String mangeDeptNm) {
        this.mangeDeptNm = mangeDeptNm;
    }

//    public java.lang.String getTypOccuNm() {
//        return typOccuNm;
//    }
//
//    public void setTypOccuNm(java.lang.String typOccuNm) {
//        this.typOccuNm = typOccuNm;
//    }
//
//    public java.lang.String getPyspGrdeNm() {
//        return pyspGrdeNm;
//    }
//
//    public void setPyspGrdeNm(java.lang.String pyspGrdeNm) {
//        this.pyspGrdeNm = pyspGrdeNm;
//    }
//
//    public java.lang.String getTypOccuCd() {
//        return typOccuCd;
//    }
//
//    public void setTypOccuCd(java.lang.String typOccuCd) {
//        this.typOccuCd = typOccuCd;
//    }
//
//    public java.lang.String getPyspGrdeCd() {
//        return pyspGrdeCd;
//    }
//
//    public void setPyspGrdeCd(java.lang.String pyspGrdeCd) {
//        this.pyspGrdeCd = pyspGrdeCd;
//    }

    public java.lang.String getPayrMangDeptCd() {
        return payrMangDeptCd;
    }

    public void setPayrMangDeptCd(java.lang.String payrMangDeptCd) {
        this.payrMangDeptCd = payrMangDeptCd;
    }

    public java.lang.String getMangeDeptCd() {
        return mangeDeptCd;
    }

    public void setMangeDeptCd(java.lang.String mangeDeptCd) {
        this.mangeDeptCd = mangeDeptCd;
    }

    public java.lang.String getSystemkey() {
        return systemkey;
    }

    public void setSystemkey(java.lang.String systemkey) {
        this.systemkey = systemkey;
    }

    public java.lang.String getDeptCd() {
        return deptCd;
    }

    public void setDeptCd(java.lang.String deptCd) {
        this.deptCd = deptCd;
    }

    public java.lang.String getUsrTel() {
        return usrTel;
    }

    public void setUsrTel(java.lang.String usrTel) {
        this.usrTel = usrTel;
    }

    public java.lang.String getDpobCd() {
		return dpobCd;
	} 

	public void setDpobCd(java.lang.String dpobCd) {
		this.dpobCd = dpobCd;
	}
 
    
    public java.lang.String getSysDivCd() {
        return this.sysDivCd;
    }
    
    public void setSysDivCd(java.lang.String sysDivCd) {
        this.sysDivCd = sysDivCd;
    }
    
    public java.lang.String getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(java.lang.String usrId) {
        this.usrId = usrId;
    }
    
    public java.lang.String getUsrNm() {
        return this.usrNm;
    }
    
    public void setUsrNm(java.lang.String usrNm) {
        this.usrNm = usrNm;
    }
    
    public java.lang.String getUsrDivCd() {
        return this.usrDivCd;
    }
    
    public void setUsrDivCd(java.lang.String usrDivCd) {
        this.usrDivCd = usrDivCd;
    }
    
    public java.lang.String getEmail() {
        return this.email;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public java.lang.String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(java.lang.String pwd) {
        this.pwd = pwd;
    }
    
    public java.lang.String getUseYn() {
        return this.useYn;
    }
    
    public void setUseYn(java.lang.String useYn) {
        this.useYn = useYn;
    }
    
    public java.lang.String getKybdr() {
        return this.kybdr;
    }
    
    public void setKybdr(java.lang.String kybdr) {
        this.kybdr = kybdr;
    }
    
    public java.lang.String getInptDt() {
        return this.inptDt;
    }
    
    public void setInptDt(java.lang.String inptDt) {
        this.inptDt = inptDt;
    }
    
    public java.lang.String getInptAddr() {
        return this.inptAddr;
    }
    
    public void setInptAddr(java.lang.String inptAddr) {
        this.inptAddr = inptAddr;
    }
    
    public java.lang.String getIsmt() {
        return this.ismt;
    }
    
    public void setIsmt(java.lang.String ismt) {
        this.ismt = ismt;
    }
    
    public java.lang.String getRevnDt() {
        return this.revnDt;
    }
    
    public void setRevnDt(java.lang.String revnDt) {
        this.revnDt = revnDt;
    }
    
    public java.lang.String getRevnAddr() {
        return this.revnAddr;
    }
    
    public void setRevnAddr(java.lang.String revnAddr) {
        this.revnAddr = revnAddr;
    }
    

//    public Set getAdmMenuUsers() {
//        return this.admMenuUsers;
//    }
//
//    public void setAdmMenuUsers(Set admMenuUsers) {
//        this.admMenuUsers = admMenuUsers;
//    }

    public Set getAdmTraceUsers() {
        return this.admTraceUsers;
    }

    public void setAdmTraceUsers(Set admTraceUsers) {
        this.admTraceUsers = admTraceUsers;
    }

    public Set getAdmDataHistories() {
        return this.admDataHistories;
    }

    public void setAdmDataHistories(Set admDataHistories) {
        this.admDataHistories = admDataHistories;
    }

    public Set getAdmSysm0500() {
        return this.admSysm0500;
    }

    public void setAdmSysm0500(Set admSysm0500) {
        this.admSysm0500 = admSysm0500;
    }
    
    public Set getAdmSsoxUser() {
        return this.admSsoxUser;
    }

    public void setAdmSsoxUser(Set admSsoxUser) {
        this.admSsoxUser = admSsoxUser;
    }
    
    public Set getAdmUserInfo() {
        return this.admUserInfo;
    }

    public void setAdmUserInfo(Set admUserInfo) {
        this.admUserInfo = admUserInfo;
    }

	public Set getAdmAuthCheckInfo() {
		return this.admAuthCheckInfo;
	}

	public void setAdmAuthCheckInfo(Set admAuthCheckInfo) {
		this.admAuthCheckInfo = admAuthCheckInfo;
	}

	public java.lang.String getTmpPwd() {
		return tmpPwd;
	}

	public void setTmpPwd(java.lang.String tmpPwd) {
		this.tmpPwd = tmpPwd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getSsoUseType()
	 * @brief date:2017 2017. 6. 1. user:atres
	 * @return the ssoUseType get
	 */
	public java.lang.String getSsoUseType() {
		return ssoUseType;
	}

	/**
	 * Comment : 
	 *@fn void setSsoUseType(java.lang.String ssoUseType)
	 *@brief date:2017 2017. 6. 1. user:atres
	 *@param ssoUseType the ssoUseType to set
	 */
	public void setSsoUseType(java.lang.String ssoUseType) {
		this.ssoUseType = ssoUseType;
	}

	public java.lang.String getDtilOccuInttnCd() {
		return dtilOccuInttnCd;
	}

	public void setDtilOccuInttnCd(java.lang.String dtilOccuInttnCd) {
		this.dtilOccuInttnCd = dtilOccuInttnCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getAuthInStdt()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the authInStdt get
	 */
	public java.lang.String getAuthInStdt() {
		return authInStdt;
	}

	/**
	 * Comment : 
	 *@fn void setAuthInStdt(java.lang.String authInStdt)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param authInStdt the authInStdt to set
	 */
	public void setAuthInStdt(java.lang.String authInStdt) {
		this.authInStdt = authInStdt;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getAuthInEddt()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the authInEddt get
	 */
	public java.lang.String getAuthInEddt() {
		return authInEddt;
	}

	/**
	 * Comment : 
	 *@fn void setAuthInEddt(java.lang.String authInEddt)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param authInEddt the authInEddt to set
	 */
	public void setAuthInEddt(java.lang.String authInEddt) {
		this.authInEddt = authInEddt;
	}

	/**
	 * Comment : 
	 * @fn java.math.BigDecimal getUsrLgnCntChk()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the usrLgnCntChk get
	 */
	public java.math.BigDecimal getUsrLgnCntChk() {
		return usrLgnCntChk;
	}

	/**
	 * Comment : 
	 *@fn void setUsrLgnCntChk(java.math.BigDecimal usrLgnCntChk)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param usrLgnCntChk the usrLgnCntChk to set
	 */
	public void setUsrLgnCntChk(java.math.BigDecimal usrLgnCntChk) {
		this.usrLgnCntChk = usrLgnCntChk;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getUsrLgnSessn()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the usrLgnSessn get
	 */
	public java.lang.String getUsrLgnSessn() {
		return usrLgnSessn;
	}

	/**
	 * Comment : 
	 *@fn void setUsrLgnSessn(java.lang.String usrLgnSessn)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param usrLgnSessn the usrLgnSessn to set
	 */
	public void setUsrLgnSessn(java.lang.String usrLgnSessn) {
		this.usrLgnSessn = usrLgnSessn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getUsrLgnDttm()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the usrLgnDttm get
	 */
	public java.lang.String getUsrLgnDttm() {
		return usrLgnDttm;
	}

	/**
	 * Comment : 
	 *@fn void setUsrLgnDttm(java.lang.String usrLgnDttm)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param usrLgnDttm the usrLgnDttm to set
	 */
	public void setUsrLgnDttm(java.lang.String usrLgnDttm) {
		this.usrLgnDttm = usrLgnDttm;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getUsrLgnAccLckYn()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the usrLgnAccLckYn get
	 */
	public java.lang.String getUsrLgnAccLckYn() {
		return usrLgnAccLckYn;
	}

	/**
	 * Comment : 
	 *@fn void setUsrLgnAccLckYn(java.lang.String usrLgnAccLckYn)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param usrLgnAccLckYn the usrLgnAccLckYn to set
	 */
	public void setUsrLgnAccLckYn(java.lang.String usrLgnAccLckYn) {
		this.usrLgnAccLckYn = usrLgnAccLckYn;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getUntDpobCd()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the untDpobCd get
	 */
	public java.lang.String getUntDpobCd() {
		return untDpobCd;
	}

	/**
	 * Comment : 
	 *@fn void setUntDpobCd(java.lang.String untDpobCd)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param untDpobCd the untDpobCd to set
	 */
	public void setUntDpobCd(java.lang.String untDpobCd) {
		this.untDpobCd = untDpobCd;
	}

	/**
	 * Comment : 
	 * @fn java.lang.String getPayMangeDeptCd()
	 * @brief date:2017 2017. 12. 8. user:atres
	 * @return the payMangeDeptCd get
	 */
	public java.lang.String getPayMangeDeptCd() {
		return payMangeDeptCd;
	}

	/**
	 * Comment : 
	 *@fn void setPayMangeDeptCd(java.lang.String payMangeDeptCd)
	 *@brief date:2017 2017. 12. 8. user:atres
	 *@param payMangeDeptCd the payMangeDeptCd to set
	 */
	public void setPayMangeDeptCd(java.lang.String payMangeDeptCd) {
		this.payMangeDeptCd = payMangeDeptCd;
	}

	
	public java.lang.String getLockat() {
		return lockat;
	}

	public void setLockat(java.lang.String lockat) {
		this.lockat = lockat;
	}


	public java.lang.String getLogincnt() {
		return logincnt;
	}

	public void setLogincnt(java.lang.String logincnt) {
		this.logincnt = logincnt;
	}

	public java.lang.String getPwddate() {
		return pwddate;
	}

	public void setPwddate(java.lang.String pwddate) {
		this.pwddate = pwddate;
	}
	
	
  
	
}
