/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.core.msfmainapp.server.vo.system;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

/**
 * AdmColumnObjectDbId generated by hbm2java
 */
public class AdmColumnObjectDbId implements java.io.Serializable {

    private String tableName;
    private String columnName;

    public AdmColumnObjectDbId() {
    }

    public AdmColumnObjectDbId(String tableName, String columnName) {
        this.tableName = tableName;
        this.columnName = columnName;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getColumnName() {
        return this.columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AdmColumnObjectDbId))
            return false;
        AdmColumnObjectDbId castOther = (AdmColumnObjectDbId) other;

        return ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null && castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
                && ((this.getColumnName() == castOther.getColumnName()) || (this.getColumnName() != null && castOther.getColumnName() != null && this.getColumnName().equals(castOther.getColumnName())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
        result = 37 * result + (getColumnName() == null ? 0 : this.getColumnName().hashCode());
        return result;
    }

}
