/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.core.msfmainapp.server.vo.system;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

/**
 * AdmColumnObjectDb generated by hbm2java
 */
public class AdmColumnObjectDb implements java.io.Serializable {

    private AdmColumnObjectDbId id;
    private String dataType;
    private Long dataLength;
    private Long dataScale;
    private Long dataPrecision;
    private String nullable;
    private String constraintType;

    public AdmColumnObjectDb() {
    }

    public AdmColumnObjectDb(AdmColumnObjectDbId id, Long dataLength) {
        this.id = id;
        this.dataLength = dataLength;
    }

    public AdmColumnObjectDb(AdmColumnObjectDbId id, String dataType, Long dataLength, Long dataScale, Long dataPrecision, String nullable, String constraintType) {
        this.id = id;
        this.dataType = dataType;
        this.dataLength = dataLength;
        this.dataScale = dataScale;
        this.dataPrecision = dataPrecision;
        this.nullable = nullable;
        this.constraintType = constraintType;
    }

    public AdmColumnObjectDbId getId() {
        return this.id;
    }

    public void setId(AdmColumnObjectDbId id) {
        this.id = id;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Long getDataLength() {
        return this.dataLength;
    }

    public void setDataLength(Long dataLength) {
        this.dataLength = dataLength;
    }

    public Long getDataScale() {
        return this.dataScale;
    }

    public void setDataScale(Long dataScale) {
        this.dataScale = dataScale;
    }

    public Long getDataPrecision() {
        return this.dataPrecision;
    }

    public void setDataPrecision(Long dataPrecision) {
        this.dataPrecision = dataPrecision;
    }

    public String getNullable() {
        return this.nullable;
    }

    public void setNullable(String nullable) {
        this.nullable = nullable;
    }

    public String getConstraintType() {
        return this.constraintType;
    }

    public void setConstraintType(String constraintType) {
        this.constraintType = constraintType;
    }

}
