/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.core.msfmainapp.server.vo.system;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

import java.sql.Blob;
import java.util.Date;

import com.app.smrmf.sysm.server.vo.SysIfSysm0100VO;


/**
 * AdmDataHistory generated by hbm2java
 */
public class AdmDataHistory implements java.io.Serializable {

    private Long id;
    private SysIfSysm0100VO admUser;
    private Date datetime;
    private String activityOnDb;
    private String tableName;
    private String daoName;
    private Blob dataStored;
    private String primaryKey;

    public AdmDataHistory() {
    }

    public AdmDataHistory(SysIfSysm0100VO admUser, Date datetime, String activityOnDb, String tableName, String daoName, String primaryKey) {
        this.admUser = admUser;
        this.datetime = datetime;
        this.activityOnDb = activityOnDb;
        this.tableName = tableName;
        this.daoName = daoName;
        this.primaryKey = primaryKey;
    }

    public AdmDataHistory(SysIfSysm0100VO admUser, Date datetime, String activityOnDb, String tableName, String daoName, Blob dataStored, String primaryKey) {
        this.admUser = admUser;
        this.datetime = datetime;
        this.activityOnDb = activityOnDb;
        this.tableName = tableName;
        this.daoName = daoName;
        this.dataStored = dataStored;
        this.primaryKey = primaryKey;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SysIfSysm0100VO getAdmUser() {
        return this.admUser;
    }

    public void setAdmUser(SysIfSysm0100VO admUser) {
        this.admUser = admUser;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getActivityOnDb() {
        return this.activityOnDb;
    }

    public void setActivityOnDb(String activityOnDb) {
        this.activityOnDb = activityOnDb;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getDaoName() {
        return this.daoName;
    }

    public void setDaoName(String daoName) {
        this.daoName = daoName;
    }

    public Blob getDataStored() {
        return this.dataStored;
    }

    public void setDataStored(Blob dataStored) {
        this.dataStored = dataStored;
    }

    public String getPrimaryKey() {
        return this.primaryKey;
    }

    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

}
