/*
 * Micro Smart Framework - Framework GWT (Google) + Ext GWT (Sencha) for RIA Applications
 * Copyright(c) 2014, atres
 * 
 * http://visionit.kr
 *
 */
package com.app.smrmf.core.msfmainapp.server.vo.system;

// Generated 18-mag-2010 14.14.14 by Hibernate Tools 3.2.5.Beta

/**
 * AdmObjectDb generated by hbm2java
 */
public class AdmObjectDb implements java.io.Serializable {

    private String tname;
    private String tabtype;

    public AdmObjectDb() {
    }

    public AdmObjectDb(String tname) {
        this.tname = tname;
    }

    public AdmObjectDb(String tname, String tabtype) {
        this.tname = tname;
        this.tabtype = tabtype;
    }

    public String getTname() {
        return this.tname;
    }

    public void setTname(String tname) {
        this.tname = tname;
    }

    public String getTabtype() {
        return this.tabtype;
    }

    public void setTabtype(String tabtype) {
        this.tabtype = tabtype;
    }

}
